version: 2.0
jobs:
 build:
   docker:
     - image: microsoft/aspnetcore-build:lts
   steps:
     - checkout
     - run:
         name: Restore packages
         command:
           dotnet restore WorkShopCore/WorkShopCore.sln
     - run:
         name: Build App
         command:
           dotnet build WorkShopCore/src/unittest/project.json
     - run:
         name: Run Test
         command:
           dotnet test WorkShopCore/src/unittest/project.json --no-build
