version: 2.0
jobs:
 build:
   docker:
     - image: microsoft/aspnetcore:1.1
   steps:
     - checkout
     - run:
         name: Restore packages
         command:
           dotnet restore
     - run:
         name: Build App
         command:
           dotnet build
     - run:
         name: Run Test
         command:
           dotnet test --no-build
